name: deploy
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  call-in-progress-notify:
    uses: ./.github/workflows/inProgressNotify.yml
    with:
      channelId: ${{ vars.SLACK_DEPLOY_CHANNEL_ID }}
    secrets:
      slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}

  deploy:
    needs: call-in-progress-notify
    uses: ./.github/workflows/sshDeploy.yml
    with:
      repoName: ${{ vars.REPO_NAME }}
    secrets:
      sshHost: ${{ secrets.SSH_HOST }}
      sshUser: ${{ secrets.SSH_USER }}
      sshPrivateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      sshPort: ${{ secrets.SSH_PORT }}

  call-complete-notify:
    needs: [body, call-in-progress-notify]
    uses: ./.github/workflows/completeNotify.yml
    with:
      ts: ${{ needs.call-in-progress-notify.outputs.ts }}
      time: ${{ needs.call-in-progress-notify.outputs.time }}
      channelId: ${{ vars.SLACK_DEPLOY_CHANNEL_ID }}
    secrets:
      slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}

  call-failure-notify:
    needs: [body, call-in-progress-notify]
    if: ${{ failure() }}
    uses: ./.github/workflows/failureNotify.yml
    with:
      ts: ${{ needs.call-in-progress-notify.outputs.ts }}
      time: ${{ needs.call-in-progress-notify.outputs.time }}
      channelId: ${{ vars.SLACK_DEPLOY_CHANNEL_ID }}
    secrets:
      slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
